/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIINTERFACE;

import javax.swing.*;
import java.awt.event.*;
/*
 * @author kurvy morales and emmanuel ting
 */

/**
 * The MainMenuAndCreateMachineView class represents the graphical user interface (GUI) 
 * for the main menu and vending machine creation view of the vending machine application.
 * It extends the javax.swing.JFrame class to create a window with various GUI components
 * for user interaction. The class includes buttons, labels, radio buttons, text fields, and
 * a text area for displaying the list of items in the vending machine.
 */
public class MainMenuAndCreateMachineView extends javax.swing.JFrame {
    /**
     * Creates the main frame for the vending machine GUI.
     */
    private JFrame CreateMachine;
    
    /**
     * A group of radio buttons to select the type of vending machine to create.
     */
    private ButtonGroup buttonGroup;
    
    /**
     * A button to exit the vending machine GUI application.
     */
    private JButton ExitButton;
    
    /**
     * A button to create a new vending machine.
     */
    private JButton CreateVendingMachine;
    
    /**
     * A button to test the existing vending machine.
     */
    private JButton TestVendingMachine;
    
    /**
     * A button to confirm and create the vending machine.
     */
    private JButton CreateMachineButton;
    
    /**
     * A label to display information or messages in the GUI.
     */
    private JLabel jLabel1;
    
    /**
     * A label to display information or messages in the GUI.
     */
    private JLabel jLabel2;
    
    /**
     * A label to display information about the selected item in the vending machine.
     */
    private JLabel ItemDisplayLabel;
    
    /**
     * A label to display information or messages in the GUI.
     */
    private JLabel jLabel4;
    
    /**
     * A panel to group and organize GUI components.
     */
    private JPanel jPanel1;
    
    /**
     * A panel to group and organize GUI components.
     */
    private JPanel jPanel2;
    
    /**
     * A panel to group and organize GUI components.
     */
    private JPanel jPanel3;
    
    /**
     * A radio button to select a regular vending machine.
     */
    private JRadioButton RegMachineButton;
    
    /**
     * A radio button to select a special vending machine.
     */
    private JRadioButton SpecialMachineButton;
    
    /**
     * A scrollable pane to display the list of items in the vending machine.
     */
    private JScrollPane jScrollPane1;
    
    /**
     * A text area to display the list of items in the vending machine.
     */
    private JTextArea ItemListDisplay;
    
    /**
     * A text field to enter input or display information in the GUI.
     */
    private JTextField jTextField1;
    
    /**
     * Constructs the main menu and vending machine creation view.
     * This constructor initializes and sets up the graphical components of the view.
     */
    public MainMenuAndCreateMachineView() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        CreateMachine = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RegMachineButton = new javax.swing.JRadioButton();
        SpecialMachineButton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        ItemDisplayLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ItemListDisplay = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CreateMachineButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        CreateVendingMachine = new javax.swing.JButton();
        TestVendingMachine = new javax.swing.JButton();

        CreateMachine.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CreateMachine.setResizable(false);
        CreateMachine.setSize(new java.awt.Dimension(807, 420));
        CreateMachine.setType(java.awt.Window.Type.POPUP);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Create your Vending Machine");

        buttonGroup.add(RegMachineButton);
        RegMachineButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegMachineButton.setText("Regular Vending Machine");

        buttonGroup.add(SpecialMachineButton);
        SpecialMachineButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SpecialMachineButton.setText("Special Vending Machine");

        ItemDisplayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ItemDisplayLabel.setText("Items in the Machine: ");

        ItemListDisplay.setEditable(false);
        ItemListDisplay.setColumns(20);
        ItemListDisplay.setRows(5);
        ItemListDisplay.setText("Item 1\nItem 2\nItem 3\nItem 4\nItem 5\nItem 6\nItem 7\nItem 8\nItem 9\nIngredient 1\nIngredient 2\nIngredient 3\nIngredient 4\nIngredient 5\nIngredient 6\n");
        ItemListDisplay.setFocusable(false);
        jScrollPane1.setViewportView(ItemListDisplay);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Enter your Vending Machine Name:");

        CreateMachineButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateMachineButton.setText("Create Machine");
        CreateMachineButton.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SpecialMachineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegMachineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(CreateMachineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RegMachineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpecialMachineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CreateMachineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout CreateMachineLayout = new javax.swing.GroupLayout(CreateMachine.getContentPane());
        CreateMachine.getContentPane().setLayout(CreateMachineLayout);
        CreateMachineLayout.setHorizontalGroup(
            CreateMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateMachineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        CreateMachineLayout.setVerticalGroup(
            CreateMachineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateMachineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MCO2 Vending Machine");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        jLabel1.setText("MCO2 Vending Machine");

        ExitButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ExitButton.setText("Exit Program");

        CreateVendingMachine.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        CreateVendingMachine.setText("Create Vending Machine");

        TestVendingMachine.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        TestVendingMachine.setText("Test Vending Machine");
        TestVendingMachine.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestVendingMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateVendingMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(CreateVendingMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TestVendingMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        getAccessibleContext().setAccessibleName("FirstFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Gets the button group that contains the radio buttons for selecting the type of vending machine.
     *
     * @return The button group containing the radio buttons.
     */
    public ButtonGroup getButtonGroup() {
        return this.buttonGroup;
    }

    /**
     * Gets the radio button for selecting a regular vending machine.
     *
     * @return The radio button for selecting a regular vending machine.
     */
    public JRadioButton getRegMachineButton() {
        return this.RegMachineButton;
    }

    /**
     * Gets the radio button for selecting a special vending machine.
     *
     * @return The radio button for selecting a special vending machine.
     */
    public JRadioButton getSpecialMachineButton() {
        return this.SpecialMachineButton;
    }
    
    /**
     * Sets the text displayed in the item list display area.
     *
     * @param text The text to be displayed in the item list display area.
     */
    public void setItemListDisplayText(String text) {
        ItemListDisplay.setText(text);
    }

    /**
     * Enables or disables the "Test Vending Machine" button.
     *
     * @param value {@code true} to enable the button, {@code false} to disable it.
     */
    public void setTestVendingMachineEnabled(boolean value) {
        TestVendingMachine.setEnabled(value);
    }

    /**
     * Disposes of the "Create Machine" frame, closing the vending machine creation view.
     */
    public void disposeCreateMachine() {
        this.CreateMachine.dispose();
    }

    /**
     * Checks if the radio button for selecting a regular vending machine is currently selected.
     *
     * @return {@code true} if the regular vending machine radio button is selected, otherwise {@code false}.
     */
    public boolean isRegMachineButtonSelected() {
        return this.RegMachineButton.isSelected();
    }

    /**
     * Checks if the radio button for selecting a special vending machine is currently selected.
     *
     * @return {@code true} if the special vending machine radio button is selected, otherwise {@code false}.
     */
    public boolean isSpecialMachineButtonSelected() {
        return this.SpecialMachineButton.isSelected();
    }

    /**
     * Sets the text in the machine name text field.
     *
     * @param text The text to be set in the machine name text field.
     */
    public void setMachineNameTextField(String text) {
        this.jTextField1.setText(text);
    }

    /**
     * Gets the text from the machine name text field.
     *
     * @return The text from the machine name text field.
     */
    public String getMachineNameTextField() {
        return this.jTextField1.getText();
    }
    
     /**
     * Sets the visibility of the "Create Machine" frame.
     *
     * @param value {@code true} to make the "Create Machine" frame visible, {@code false} to hide it.
     */
    public void setCreateMachineVisible(boolean value) {
        this.CreateMachine.setVisible(value);
    }

    /**
     * Enables or disables the "Create Machine" button.
     *
     * @param value {@code true} to enable the button, {@code false} to disable it.
     */
    public void setCreateMachineButtonEnabled(boolean value) {
        this.CreateMachineButton.setEnabled(value);
    }

    /**
     * Sets an action listener to the "Exit Button".
     *
     * @param actionlistener The action listener to be attached to the "Exit Button".
     */
    public void setExitButtonListener(ActionListener actionlistener) {
        this.ExitButton.addActionListener(actionlistener);
    }

    /**
     * Sets an action listener to the "Test Vending Machine" button.
     *
     * @param actionlistener The action listener to be attached to the "Test Vending Machine" button.
     */
    public void setBtnTestVendingMachineListener(ActionListener actionlistener) {
        this.TestVendingMachine.addActionListener(actionlistener);
    }

    /**
     * Sets an action listener to the "Create Vending Machine" button.
     *
     * @param actionlistener The action listener to be attached to the "Create Vending Machine" button.
     */
    public void setCreateVendingBtnListener(ActionListener actionlistener) {
        this.CreateVendingMachine.addActionListener(actionlistener);
    }

    /**
     * Sets an action listener to the "Regular Vending Machine" radio button.
     *
     * @param actionlistener The action listener to be attached to the "Regular Vending Machine" radio button.
     */
    public void setRegMachineButtonListener(ActionListener actionlistener) {
        this.RegMachineButton.addActionListener(actionlistener);
    }

    /**
     * Sets an action listener to the "Special Vending Machine" radio button.
     *
     * @param actionlistener The action listener to be attached to the "Special Vending Machine" radio button.
     */
    public void setSpecialMachineButtonListener(ActionListener actionlistener) {
        this.SpecialMachineButton.addActionListener(actionlistener);
    }

    /**
     * Sets an action listener to the "Create Machine" button.
     *
     * @param actionlistener The action listener to be attached to the "Create Machine" button.
     */
    public void setCreateMachineButtonListener(ActionListener actionlistener) {
        this.CreateMachineButton.addActionListener(actionlistener);
    }

}
/* DEFAULT VARIABLE DECLARATION FROM NETBEANS
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame CreateMachine;
    private javax.swing.JButton CreateMachineButton;
    private javax.swing.JButton CreateVendingMachine;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel ItemDisplayLabel;
    private javax.swing.JTextArea ItemListDisplay;
    private javax.swing.JRadioButton RegMachineButton;
    private javax.swing.JRadioButton SpecialMachineButton;
    private javax.swing.JButton TestVendingMachine;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
*/
