/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIINTERFACE;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author kurvy morales & emmanuel ting
 */
public class RegMachineView extends javax.swing.JFrame {
    private JSpinner SpinnerQuantity;
    private JLabel QuantityLabel;
    private JLabel InputLabel;
    private JPanel BuyItemPanel;
    private JButton DispenseButton;
    private JButton CustomItemBuy;
    private JButton Ing1Buy;
    private JButton Ing2Buy;
    private JButton Ing3Buy;
    private JButton InsertMoneyButton;
    private JButton Item1Buy;
    private JLabel Item1Label;
    private JLabel Ing2Label;
    private JLabel Ing3Label;
    private JLabel Ing1Label;
    private JButton Item2Buy;
    private JLabel Item2Label;
    private JButton Item3Buy;
    private JLabel Item3Label;
    private JButton Item4Buy;
    private JLabel Item4Label;
    private JButton Item5Buy;
    private JLabel Item5Label;
    private JButton Item6Buy;
    private JLabel Item6Label;
    private JButton Item7Buy;
    private JLabel Item7Label;
    private JButton Item8Buy;
    private JLabel Item8Label;
    private JLabel CustomItemLabel;
    private JLabel MachineBalLabel;
    private JPanel MachineButtonPanel;
    private JLabel PersonBalLabel;
    private JPanel SpecialMachinePanel;
    private JFrame SpecialMachineCustom;
    private JTextArea MachinePrintDisplay;
    private JScrollPane jScrollPane4;
    private JButton jButtonCreate4;
    private JButton jButtonCreate9;
    private JButton jButtonCreate0;
    private JButton EnterButton;
    private JButton jButtonCreate3;
    private JButton AdminSettingsButton;
    private JLabel MaintenanceLabel;
    private JButton jButtonCreate2;
    private JButton ExitButton;
    private JButton AdminBackButton;
    private JButton jButtonCreate1;
    private JButton jButtonCreate6;
    private JButton jButtonCreate8;
    private JButton jButtonCreate7;
    private JButton jButtonCreate5;
    private JButton ClearButton;
    private JFrame AdminFrame;
    private JLabel VendingMachineName;
    private JPanel BigMachinePanel;
    private JPanel InputPanel;
    private JPanel LayoutPanel;
    private JPanel AdminPanel;
    private JScrollPane jScrollPane2;
    private JTextArea AdminDisplayArea;
    private JScrollPane jScrollPane3;
    private JTextArea NumPadDisplay;
    private int balLabel;
    
    public RegMachineView() {
        /**
         * TODO: CONNECT EACH VIEW USING CONTROLLER IN MVC)
         */
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminFrame = new javax.swing.JFrame();
        AdminPanel = new javax.swing.JPanel();
        AdminBackButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AdminDisplayArea = new javax.swing.JTextArea();
        MaintenanceLabel = new javax.swing.JLabel();
        SpecialMachineCustom = new javax.swing.JFrame();
        SpecialMachinePanel = new javax.swing.JPanel();
        BigMachinePanel = new javax.swing.JPanel();
        VendingMachineName = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        ClearButton = new javax.swing.JButton();
        EnterButton = new javax.swing.JButton();
        InsertMoneyButton = new javax.swing.JButton();
        MachineButtonPanel = new javax.swing.JPanel();
        jButtonCreate1 = new javax.swing.JButton();
        jButtonCreate2 = new javax.swing.JButton();
        jButtonCreate3 = new javax.swing.JButton();
        jButtonCreate4 = new javax.swing.JButton();
        jButtonCreate5 = new javax.swing.JButton();
        jButtonCreate6 = new javax.swing.JButton();
        jButtonCreate7 = new javax.swing.JButton();
        jButtonCreate8 = new javax.swing.JButton();
        jButtonCreate9 = new javax.swing.JButton();
        jButtonCreate0 = new javax.swing.JButton();
        LayoutPanel = new javax.swing.JPanel();
        AdminSettingsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        MachineBalLabel = new javax.swing.JLabel();
        PersonBalLabel = new javax.swing.JLabel();
        DispenseButton = new javax.swing.JButton();
        BuyItemPanel = new javax.swing.JPanel();
        Item1Label = new javax.swing.JLabel();
        Item2Label = new javax.swing.JLabel();
        Item3Label = new javax.swing.JLabel();
        Item4Label = new javax.swing.JLabel();
        Item1Buy = new javax.swing.JButton();
        Item2Buy = new javax.swing.JButton();
        Item3Buy = new javax.swing.JButton();
        Item4Buy = new javax.swing.JButton();
        Item5Label = new javax.swing.JLabel();
        Item6Label = new javax.swing.JLabel();
        Item7Label = new javax.swing.JLabel();
        Item8Label = new javax.swing.JLabel();
        Item5Buy = new javax.swing.JButton();
        Item6Buy = new javax.swing.JButton();
        Item7Buy = new javax.swing.JButton();
        Item8Buy = new javax.swing.JButton();
        CustomItemLabel = new javax.swing.JLabel();
        Ing1Label = new javax.swing.JLabel();
        Ing2Label = new javax.swing.JLabel();
        Ing3Label = new javax.swing.JLabel();
        CustomItemBuy = new javax.swing.JButton();
        Ing1Buy = new javax.swing.JButton();
        Ing2Buy = new javax.swing.JButton();
        Ing3Buy = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        NumPadDisplay = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        MachinePrintDisplay = new javax.swing.JTextArea();
        InputLabel = new javax.swing.JLabel();
        QuantityLabel = new javax.swing.JLabel();
        SpinnerQuantity = new javax.swing.JSpinner();

        AdminFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AdminFrame.setSize(new java.awt.Dimension(632, 632));

        AdminPanel.setBackground(new java.awt.Color(204, 204, 204));

        AdminBackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AdminBackButton.setText("Back to previous menu");
        AdminBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBackButtonActionPerformed(evt);
            }
        });

        AdminDisplayArea.setColumns(20);
        AdminDisplayArea.setLineWrap(true);
        AdminDisplayArea.setRows(6);
        AdminDisplayArea.setWrapStyleWord(true);
        AdminDisplayArea.setFocusable(false);
        jScrollPane2.setViewportView(AdminDisplayArea);

        MaintenanceLabel.setBackground(new java.awt.Color(255, 204, 102));
        MaintenanceLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        MaintenanceLabel.setForeground(new java.awt.Color(255, 102, 255));
        MaintenanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaintenanceLabel.setText("Maintenance Panel (Admins Only)");
        MaintenanceLabel.setAlignmentY(0.0F);
        MaintenanceLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MaintenanceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MaintenanceLabel.setMaximumSize(new java.awt.Dimension(50, 34));
        MaintenanceLabel.setMinimumSize(new java.awt.Dimension(50, 34));
        MaintenanceLabel.setName(""); // NOI18N
        MaintenanceLabel.setOpaque(true);
        MaintenanceLabel.setPreferredSize(new java.awt.Dimension(50, 34));

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addComponent(MaintenanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(AdminBackButton)
                        .addGap(69, 69, 69))))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaintenanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminBackButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdminFrameLayout = new javax.swing.GroupLayout(AdminFrame.getContentPane());
        AdminFrame.getContentPane().setLayout(AdminFrameLayout);
        AdminFrameLayout.setHorizontalGroup(
            AdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AdminFrameLayout.setVerticalGroup(
            AdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SpecialMachineCustom.setResizable(false);
        SpecialMachineCustom.setSize(new java.awt.Dimension(450, 330));
        SpecialMachineCustom.setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout SpecialMachinePanelLayout = new javax.swing.GroupLayout(SpecialMachinePanel);
        SpecialMachinePanel.setLayout(SpecialMachinePanelLayout);
        SpecialMachinePanelLayout.setHorizontalGroup(
            SpecialMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        SpecialMachinePanelLayout.setVerticalGroup(
            SpecialMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SpecialMachineCustomLayout = new javax.swing.GroupLayout(SpecialMachineCustom.getContentPane());
        SpecialMachineCustom.getContentPane().setLayout(SpecialMachineCustomLayout);
        SpecialMachineCustomLayout.setHorizontalGroup(
            SpecialMachineCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecialMachineCustomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SpecialMachinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SpecialMachineCustomLayout.setVerticalGroup(
            SpecialMachineCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecialMachineCustomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SpecialMachinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vending Machine MCO2");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(927, 651));

        BigMachinePanel.setBackground(new java.awt.Color(204, 204, 204));
        BigMachinePanel.setMaximumSize(new java.awt.Dimension(1000, 1000));

        VendingMachineName.setBackground(new java.awt.Color(255, 204, 102));
        VendingMachineName.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        VendingMachineName.setForeground(new java.awt.Color(255, 102, 255));
        VendingMachineName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VendingMachineName.setText("Vending Machine Name Here");
        VendingMachineName.setAlignmentY(0.0F);
        VendingMachineName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VendingMachineName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        VendingMachineName.setMaximumSize(new java.awt.Dimension(50, 34));
        VendingMachineName.setMinimumSize(new java.awt.Dimension(50, 34));
        VendingMachineName.setName(""); // NOI18N
        VendingMachineName.setOpaque(true);
        VendingMachineName.setPreferredSize(new java.awt.Dimension(50, 34));

        InputPanel.setBackground(new java.awt.Color(255, 255, 255));

        ClearButton.setText("CLEAR");

        EnterButton.setText("ENTER");

        InsertMoneyButton.setText("Insert Money");

        MachineButtonPanel.setBackground(new java.awt.Color(204, 255, 255));

        jButtonCreate1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate1.setText("1");

        jButtonCreate2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate2.setText("2");

        jButtonCreate3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate3.setText("3");

        jButtonCreate4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate4.setText("4");

        jButtonCreate5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate5.setText("5");

        jButtonCreate6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate6.setText("6");

        jButtonCreate7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate7.setText("7");

        jButtonCreate8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate8.setText("8");

        jButtonCreate9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate9.setText("9");

        jButtonCreate0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate0.setText("0");

        javax.swing.GroupLayout MachineButtonPanelLayout = new javax.swing.GroupLayout(MachineButtonPanel);
        MachineButtonPanel.setLayout(MachineButtonPanelLayout);
        MachineButtonPanelLayout.setHorizontalGroup(
            MachineButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MachineButtonPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(MachineButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MachineButtonPanelLayout.createSequentialGroup()
                        .addComponent(jButtonCreate1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate4)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate5))
                    .addGroup(MachineButtonPanelLayout.createSequentialGroup()
                        .addComponent(jButtonCreate6)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate7)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate8)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate9)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate0)))
                .addGap(20, 20, 20))
        );
        MachineButtonPanelLayout.setVerticalGroup(
            MachineButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MachineButtonPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(MachineButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreate5)
                    .addComponent(jButtonCreate4)
                    .addComponent(jButtonCreate3)
                    .addComponent(jButtonCreate2)
                    .addComponent(jButtonCreate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MachineButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreate6)
                    .addComponent(jButtonCreate7)
                    .addComponent(jButtonCreate0)
                    .addComponent(jButtonCreate8)
                    .addComponent(jButtonCreate9))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(EnterButton)
                        .addGap(12, 12, 12)
                        .addComponent(InsertMoneyButton))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(MachineButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(MachineButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton)
                    .addComponent(EnterButton)
                    .addComponent(InsertMoneyButton))
                .addGap(20, 20, 20))
        );

        LayoutPanel.setMaximumSize(new java.awt.Dimension(526, 486));
        LayoutPanel.setMinimumSize(new java.awt.Dimension(526, 486));

        AdminSettingsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminSettingsButton.setText("ADMIN SETTINGS");
        AdminSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminSettingsButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ExitButton.setText("EXIT MACHINE");

        MachineBalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MachineBalLabel.setText("MACHINE BALANCE: 0");

        PersonBalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PersonBalLabel.setText("BALANCE: 0");

        DispenseButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DispenseButton.setText("DISPENSE");

        BuyItemPanel.setBackground(new java.awt.Color(204, 204, 204));
        BuyItemPanel.setMaximumSize(new java.awt.Dimension(481, 349));
        BuyItemPanel.setLayout(new java.awt.GridLayout(6, 4, 15, 5));

        Item1Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item1Label.setText(" ITEM 1");
        Item1Label.setAlignmentX(5.0F);
        Item1Label.setAlignmentY(5.0F);
        Item1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuyItemPanel.add(Item1Label);

        Item2Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item2Label.setText(" ITEM 2");
        Item2Label.setAlignmentY(0.0F);
        Item2Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BuyItemPanel.add(Item2Label);

        Item3Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item3Label.setText(" ITEM 3");
        Item3Label.setAlignmentY(0.0F);
        Item3Label.setAutoscrolls(true);
        Item3Label.setFocusable(false);
        Item3Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Item3Label.setVerifyInputWhenFocusTarget(false);
        BuyItemPanel.add(Item3Label);

        Item4Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item4Label.setText(" ITEM 4");
        Item4Label.setAlignmentY(0.0F);
        Item4Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BuyItemPanel.add(Item4Label);

        Item1Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item1Buy.setText("BUY");
        BuyItemPanel.add(Item1Buy);

        Item2Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item2Buy.setText("BUY");
        BuyItemPanel.add(Item2Buy);

        Item3Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item3Buy.setText("BUY");
        BuyItemPanel.add(Item3Buy);

        Item4Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item4Buy.setText("BUY");
        BuyItemPanel.add(Item4Buy);

        Item5Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item5Label.setText(" ITEM 5");
        Item5Label.setAlignmentY(0.0F);
        Item5Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuyItemPanel.add(Item5Label);

        Item6Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item6Label.setText(" ITEM 6 ");
        Item6Label.setAlignmentY(0.0F);
        Item6Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuyItemPanel.add(Item6Label);

        Item7Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item7Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item7Label.setText(" ITEM 7");
        Item7Label.setAlignmentY(0.0F);
        Item7Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuyItemPanel.add(Item7Label);

        Item8Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item8Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item8Label.setText(" ITEM 8");
        Item8Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuyItemPanel.add(Item8Label);

        Item5Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item5Buy.setText("BUY");
        BuyItemPanel.add(Item5Buy);

        Item6Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item6Buy.setText("BUY");
        BuyItemPanel.add(Item6Buy);

        Item7Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item7Buy.setText("BUY");
        BuyItemPanel.add(Item7Buy);

        Item8Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item8Buy.setText("BUY");
        BuyItemPanel.add(Item8Buy);

        CustomItemLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CustomItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomItemLabel.setText("CUSTOM ITEM");
        CustomItemLabel.setEnabled(false);
        CustomItemLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuyItemPanel.add(CustomItemLabel);

        Ing1Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ing1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ing1Label.setText("ING 1");
        Ing1Label.setEnabled(false);
        Ing1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuyItemPanel.add(Ing1Label);

        Ing2Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ing2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ing2Label.setText("ING 2");
        Ing2Label.setEnabled(false);
        Ing2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuyItemPanel.add(Ing2Label);

        Ing3Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ing3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ing3Label.setText("ING 3");
        Ing3Label.setEnabled(false);
        Ing3Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuyItemPanel.add(Ing3Label);

        CustomItemBuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CustomItemBuy.setText("BUY");
        CustomItemBuy.setEnabled(false);
        BuyItemPanel.add(CustomItemBuy);

        Ing1Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ing1Buy.setText("BUY");
        Ing1Buy.setEnabled(false);
        BuyItemPanel.add(Ing1Buy);

        Ing2Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ing2Buy.setText("BUY");
        Ing2Buy.setEnabled(false);
        BuyItemPanel.add(Ing2Buy);

        Ing3Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ing3Buy.setText("BUY");
        Ing3Buy.setEnabled(false);
        BuyItemPanel.add(Ing3Buy);

        javax.swing.GroupLayout LayoutPanelLayout = new javax.swing.GroupLayout(LayoutPanel);
        LayoutPanel.setLayout(LayoutPanelLayout);
        LayoutPanelLayout.setHorizontalGroup(
            LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BuyItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LayoutPanelLayout.createSequentialGroup()
                        .addComponent(AdminSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(ExitButton)
                        .addGap(15, 15, 15)
                        .addComponent(DispenseButton))
                    .addGroup(LayoutPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(MachineBalLabel)
                        .addGap(99, 99, 99)
                        .addComponent(PersonBalLabel)))
                .addGap(23, 23, 23))
        );
        LayoutPanelLayout.setVerticalGroup(
            LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(BuyItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DispenseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MachineBalLabel)
                    .addComponent(PersonBalLabel))
                .addGap(46, 46, 46))
        );

        NumPadDisplay.setEditable(false);
        NumPadDisplay.setBackground(new java.awt.Color(255, 255, 204));
        NumPadDisplay.setColumns(20);
        NumPadDisplay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NumPadDisplay.setLineWrap(true);
        NumPadDisplay.setRows(6);
        NumPadDisplay.setWrapStyleWord(true);
        NumPadDisplay.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(NumPadDisplay);

        MachinePrintDisplay.setEditable(false);
        MachinePrintDisplay.setBackground(new java.awt.Color(204, 255, 204));
        MachinePrintDisplay.setColumns(10);
        MachinePrintDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MachinePrintDisplay.setLineWrap(true);
        MachinePrintDisplay.setRows(6);
        MachinePrintDisplay.setWrapStyleWord(true);
        MachinePrintDisplay.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(MachinePrintDisplay);

        InputLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InputLabel.setText("INPUT USER BALANCE:");
        InputLabel.setAlignmentY(0.0F);
        InputLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        QuantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuantityLabel.setText("QUANTITY:");
        QuantityLabel.setAlignmentY(0.0F);
        QuantityLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SpinnerQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        SpinnerQuantity.setAlignmentX(0.0F);
        SpinnerQuantity.setAlignmentY(0.0F);
        SpinnerQuantity.setEditor(new JSpinner.DefaultEditor(SpinnerQuantity));
        SpinnerQuantity.setMaximumSize(new java.awt.Dimension(64, 22));

        javax.swing.GroupLayout BigMachinePanelLayout = new javax.swing.GroupLayout(BigMachinePanel);
        BigMachinePanel.setLayout(BigMachinePanelLayout);
        BigMachinePanelLayout.setHorizontalGroup(
            BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BigMachinePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VendingMachineName, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LayoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BigMachinePanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BigMachinePanelLayout.createSequentialGroup()
                        .addGroup(BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addComponent(jScrollPane4))
                .addGap(25, 25, 25))
        );
        BigMachinePanelLayout.setVerticalGroup(
            BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BigMachinePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BigMachinePanelLayout.createSequentialGroup()
                        .addComponent(VendingMachineName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(LayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BigMachinePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputLabel)
                            .addComponent(QuantityLabel))
                        .addGap(10, 10, 10)
                        .addGroup(BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        VendingMachineName.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BigMachinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BigMachinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setMachinePrintDisplayText(String text) {
        this.MachinePrintDisplay.setText(text);
    }
    
    public String getMachinePrintDisplayText() {
        return this.MachinePrintDisplay.getText();
    }
    
    public void setPersonBalLabelText(String text) {
        this.PersonBalLabel.setText(text);
    }
    public void setmachineLabel(String text){
        this.VendingMachineName.setText(text);
    }
    
    public void setcustomItemLabelStatus (boolean value) {
        CustomItemLabel.setEnabled(value);
    }
    
    public void setcustomItemBuyStatus (boolean value) {
        CustomItemBuy.setEnabled(value);
    }
    
    public void setIng1LabelStatus (boolean value) {
        Ing1Label.setEnabled(value);
    }
    
     public void setIng1BuyStatus (boolean value) {
        Ing1Buy.setEnabled(value);
    }
    
    public void setIng2LabelStatus (boolean value) {
        Ing2Label.setEnabled(value);
    }
    
    public void setIng2BuyStatus (boolean value) {
        Ing2Buy.setEnabled(value);
    }
    
    public void setIng3LabelStatus (boolean value) {
        Ing3Label.setEnabled(value);
    }
    
     public void setIng3BuyStatus (boolean value) {
        Ing3Buy.setEnabled(value);
    }
    public void setNumPadDisplayText (String text) {
        NumPadDisplay.setText(text);
    }
    
    public String getNumPadDisplayText() {
        return this.NumPadDisplay.getText();
    }
    
    public int getSpinnerQuantity() {
       return( (Integer) this.SpinnerQuantity.getValue() );
    }
    
    public void setSpinnerQuantity(int quantity) {
      this.SpinnerQuantity.setValue(quantity);
    }
    
    public void setItem1BuyActionListener (ActionListener actionlistener) {
        this.Item1Buy.addActionListener(actionlistener);
    }
    
    public void setItem2BuyActionListener (ActionListener actionlistener) {
        this.Item2Buy.addActionListener(actionlistener);
    }
    
    public void setItem3BuyActionListener (ActionListener actionlistener) {
        this.Item3Buy.addActionListener(actionlistener);
    }
    
    public void setItem4BuyActionListener (ActionListener actionlistener) {
        this.Item4Buy.addActionListener(actionlistener);
    }
    
    public void setItem5BuyActionListener (ActionListener actionlistener) {
        this.Item5Buy.addActionListener(actionlistener);
    }
    
    public void setItem6BuyActionListener (ActionListener actionlistener) {
        this.Item6Buy.addActionListener(actionlistener);
    }
    
    public void setItem7BuyActionListener (ActionListener actionlistener) {
        this.Item7Buy.addActionListener(actionlistener);
    }
    
    public void setItem8BuyActionListener (ActionListener actionlistener) {
        this.Item8Buy.addActionListener(actionlistener);
    }
    
    public void setCustomItemBuyActionListener (ActionListener actionlistener) {
        this.CustomItemBuy.addActionListener(actionlistener);
    }
    
    public void setIng1BuyActionListener (ActionListener actionlistener) {
        this.Ing1Buy.addActionListener(actionlistener);
    }
    
    public void setIng2BuyActionListener (ActionListener actionlistener) {
        this.Ing2Buy.addActionListener(actionlistener);
    }
    
    public void set3ng1BuyActionListener (ActionListener actionlistener) {
        this.Ing3Buy.addActionListener(actionlistener);
    }
    
    public void setItem1Label (String text) {
        this.Item1Label.setText(text);
    }
    
    public void setItem2Label (String text) {
        this.Item2Label.setText(text);
    }
     
    public void setItem3Label (String text) {
        this.Item3Label.setText(text);
    }
      
    public void setItem4Label (String text) {
        this.Item4Label.setText(text);
    }
       
    public void setItem5Label (String text) {
        this.Item5Label.setText(text);
    }
        
    public void setItem6Label (String text) {
        this.Item6Label.setText(text);
    }
         
    public void setItem7Label (String text) {
        this.Item7Label.setText(text);
    }
          
    public void setItem8Label (String text) {
        this.Item8Label.setText(text);
    }
    
    public void setCustomItemLabel (String text) {
        this.CustomItemLabel.setText(text);
    }
    
    public void setIng1Label (String text) {
        this.Ing1Label.setText(text);
    }
    
    public void setIng2Label (String text) {
        this.Ing2Label.setText(text);
    }
    
    public void setIng3Label (String text) {
        this.Ing3Label.setText(text);
    }
    
    public void setButtonCreate0ActionListener (ActionListener actionlistener) {
        this.jButtonCreate0.addActionListener(actionlistener);
    }
    
    public void setButtonCreate1ActionListener (ActionListener actionlistener) {
        this.jButtonCreate1.addActionListener(actionlistener);
    }
    
    public void setButtonCreate2ActionListener (ActionListener actionlistener) {
        this.jButtonCreate2.addActionListener(actionlistener);
    }
    
    public void setButtonCreate3ActionListener (ActionListener actionlistener) {
        this.jButtonCreate3.addActionListener(actionlistener);
    }
    
    public void setButtonCreate4ActionListener (ActionListener actionlistener) {
        this.jButtonCreate4.addActionListener(actionlistener);
    }
    
     public void setButtonCreate5ActionListener (ActionListener actionlistener) {
        this.jButtonCreate5.addActionListener(actionlistener);
    }
    
    public void setButtonCreate6ActionListener (ActionListener actionlistener) {
        this.jButtonCreate6.addActionListener(actionlistener);
    }
    
    public void setButtonCreate7ActionListener (ActionListener actionlistener) {
        this.jButtonCreate7.addActionListener(actionlistener);
    }
    
    public void setButtonCreate8ActionListener (ActionListener actionlistener) {
        this.jButtonCreate8.addActionListener(actionlistener);
    }
    
    public void setButtonCreate9ActionListener (ActionListener actionlistener) {
        this.jButtonCreate9.addActionListener(actionlistener);
    }
    
    public void setClearButtonListener(ActionListener actionlistener) {
        this.ClearButton.addActionListener(actionlistener);
    }
    
    public void setEnterButtonListener  (ActionListener actionlistener) {
        this.EnterButton.addActionListener(actionlistener);
    }
    
    public void setMachineBalance(String text) {
        MachineBalLabel.setText(text);
    }
    
    private void AdminSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminSettingsButtonActionPerformed
        AdminFrame.setVisible(true);
       // TODO add your handling code here:
    }//GEN-LAST:event_AdminSettingsButtonActionPerformed
    public void setExitButtonActionListener(ActionListener listener) {
        this.ExitButton.addActionListener(listener);
    }
    private void AdminBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBackButtonActionPerformed
        AdminFrame.dispose();
    }//GEN-LAST:event_AdminBackButtonActionPerformed
    public void setInsertMoneyButtonListener (ActionListener actionlistener) {
        this.InsertMoneyButton.addActionListener(actionlistener);
    }
    
    public void setDispenseButtonActionListener(ActionListener actionlistener) {
        this.DispenseButton.addActionListener(actionlistener);
    }
}
    /**
     * @param args the command line arguments
     */
    
    
  // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(new Runnable() {
     //       public void run() {
    //        }
    //    });
  //  } 

 
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBackButton;
    private javax.swing.JTextArea AdminDisplayArea;
    private javax.swing.JFrame AdminFrame;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JButton AdminSettingsButton;
    private javax.swing.JPanel BigMachinePanel;
    private javax.swing.JPanel BuyItemPanel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CustomItemBuy;
    private javax.swing.JLabel CustomItemLabel;
    private javax.swing.JButton DispenseButton;
    private javax.swing.JButton EnterButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton Ing1Buy;
    private javax.swing.JLabel Ing1Label;
    private javax.swing.JButton Ing2Buy;
    private javax.swing.JLabel Ing2Label;
    private javax.swing.JButton Ing3Buy;
    private javax.swing.JLabel Ing3Label;
    private javax.swing.JLabel InputLabel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JButton InsertMoneyButton;
    private javax.swing.JButton Item1Buy;
    private javax.swing.JLabel Item1Label;
    private javax.swing.JButton Item2Buy;
    private javax.swing.JLabel Item2Label;
    private javax.swing.JButton Item3Buy;
    private javax.swing.JLabel Item3Label;
    private javax.swing.JButton Item4Buy;
    private javax.swing.JLabel Item4Label;
    private javax.swing.JButton Item5Buy;
    private javax.swing.JLabel Item5Label;
    private javax.swing.JButton Item6Buy;
    private javax.swing.JLabel Item6Label;
    private javax.swing.JButton Item7Buy;
    private javax.swing.JLabel Item7Label;
    private javax.swing.JButton Item8Buy;
    private javax.swing.JLabel Item8Label;
    private javax.swing.JPanel LayoutPanel;
    private javax.swing.JLabel MachineBalLabel;
    private javax.swing.JPanel MachineButtonPanel;
    private javax.swing.JTextArea MachinePrintDisplay;
    private javax.swing.JLabel MaintenanceLabel;
    private javax.swing.JTextArea NumPadDisplay;
    private javax.swing.JLabel PersonBalLabel;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JFrame SpecialMachineCustom;
    private javax.swing.JPanel SpecialMachinePanel;
    private javax.swing.JSpinner SpinnerQuantity;
    private javax.swing.JLabel VendingMachineName;
    private javax.swing.JButton jButtonCreate0;
    private javax.swing.JButton jButtonCreate1;
    private javax.swing.JButton jButtonCreate2;
    private javax.swing.JButton jButtonCreate3;
    private javax.swing.JButton jButtonCreate4;
    private javax.swing.JButton jButtonCreate5;
    private javax.swing.JButton jButtonCreate6;
    private javax.swing.JButton jButtonCreate7;
    private javax.swing.JButton jButtonCreate8;
    private javax.swing.JButton jButtonCreate9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
*/