/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIINTERFACE;
import javax.swing.*;
/**
 *
 * @author kurvy morales & emmanuel ting
 */
public class RegMachineView extends javax.swing.JFrame {
    //private Model something something;
    private GUIModel Model;
    private javax.swing.JPanel BuyItemPanel;
    private javax.swing.JButton ExitButton1;
    private JButton Ing1Buy;
    private JButton Ing2Buy;
    private JButton Ing3Buy;
    private JButton Ing4Buy;
    private JButton InsertMoneyButton;
    private JButton Item1Buy;
    private JLabel Item1Label;
    private JLabel Item1Label10;
    private JLabel Item1Label11;
    private JLabel Item1Label9;
    private JButton Item2Buy;
    private JLabel Item2Label;
    private JButton Item3Buy;
    private JLabel Item3Label;
    private JButton Item4Buy;
    private JLabel Item4Label;
    private JButton Item5Buy;
    private JLabel Item5Label;
    private JButton Item6Buy;
    private JLabel Item6Label;
    private JButton Item7Buy;
    private JLabel Item7Label;
    private JButton Item8Buy;
    private JLabel Item8Label;
    private JLabel Item9Label;
    private JLabel MachineBalLabel;
    private JPanel MachineButtonPanel;
    private JLabel PersonBalLabel;
    private JPanel SpecialMachinePanel;
    private JFrame SpecialMachineCustom;
    private JTextArea MachinePrintDisplay;
    private JScrollPane jScrollPane4;
    private JButton jButtonCreate4;
    private JButton jButtonCreate9;
    private JButton jButtonCreate0;
    private JButton amountGetterButton;
    private JButton jButtonCreate3;
    private JButton jButton21;
    private JLabel MaintenanceLabel;
    private JButton jButtonCreate2;
    private JButton ExitButton;
    private JButton AdminBackButton;
    private JButton jButtonCreate1;
    private JButton jButtonCreate6;
    private JButton jButtonCreate8;
    private JButton jButtonCreate7;
    private JButton jButtonCreate5;
    private JButton ClearButton;
    private JFrame AdminFrameRegular;
    private JLabel VendingMachineName;
    private JPanel BigMachinePanel;
    private JPanel InputPanel;
    private JPanel LayoutPanel;
    private JPanel AdminPanel;
    private JScrollPane jScrollPane2;
    private JTextArea AdminDisplayArea;
    private JScrollPane jScrollPane3;
    private JTextArea NumPadDisplay;
    private int quantityBuy;
    private int balLabel;
    
    public RegMachineView(GUIModel model) {
        /**
         * TODO: CONNECT EACH VIEW USING CONTROLLER IN MVC)
         */
        this.quantityBuy = 0;
        this.balLabel = 0;
        this.Model = model;
        initComponents();
    }
    
    public void setmachineLabel(String text){
        this.VendingMachineName.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminFrameRegular = new javax.swing.JFrame();
        AdminPanel = new javax.swing.JPanel();
        AdminBackButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AdminDisplayArea = new javax.swing.JTextArea();
        MaintenanceLabel = new javax.swing.JLabel();
        SpecialMachineCustom = new javax.swing.JFrame();
        SpecialMachinePanel = new javax.swing.JPanel();
        BigMachinePanel = new javax.swing.JPanel();
        VendingMachineName = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        ClearButton = new javax.swing.JButton();
        amountGetterButton = new javax.swing.JButton();
        InsertMoneyButton = new javax.swing.JButton();
        MachineButtonPanel = new javax.swing.JPanel();
        jButtonCreate1 = new javax.swing.JButton();
        jButtonCreate2 = new javax.swing.JButton();
        jButtonCreate3 = new javax.swing.JButton();
        jButtonCreate4 = new javax.swing.JButton();
        jButtonCreate5 = new javax.swing.JButton();
        jButtonCreate6 = new javax.swing.JButton();
        jButtonCreate7 = new javax.swing.JButton();
        jButtonCreate8 = new javax.swing.JButton();
        jButtonCreate9 = new javax.swing.JButton();
        jButtonCreate0 = new javax.swing.JButton();
        LayoutPanel = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        MachineBalLabel = new javax.swing.JLabel();
        PersonBalLabel = new javax.swing.JLabel();
        ExitButton1 = new javax.swing.JButton();
        BuyItemPanel = new javax.swing.JPanel();
        Item1Buy = new javax.swing.JButton();
        Item2Buy = new javax.swing.JButton();
        Item3Buy = new javax.swing.JButton();
        Item4Buy = new javax.swing.JButton();
        Item5Buy = new javax.swing.JButton();
        Item6Buy = new javax.swing.JButton();
        Item8Buy = new javax.swing.JButton();
        Item7Buy = new javax.swing.JButton();
        Ing1Buy = new javax.swing.JButton();
        Ing2Buy = new javax.swing.JButton();
        Ing3Buy = new javax.swing.JButton();
        Ing4Buy = new javax.swing.JButton();
        Item1Label = new javax.swing.JLabel();
        Item2Label = new javax.swing.JLabel();
        Item4Label = new javax.swing.JLabel();
        Item3Label = new javax.swing.JLabel();
        Item5Label = new javax.swing.JLabel();
        Item6Label = new javax.swing.JLabel();
        Item7Label = new javax.swing.JLabel();
        Item8Label = new javax.swing.JLabel();
        Item9Label = new javax.swing.JLabel();
        Item1Label9 = new javax.swing.JLabel();
        Item1Label10 = new javax.swing.JLabel();
        Item1Label11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NumPadDisplay = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        MachinePrintDisplay = new javax.swing.JTextArea();

        AdminFrameRegular.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AdminFrameRegular.setSize(new java.awt.Dimension(632, 632));

        AdminPanel.setBackground(new java.awt.Color(204, 204, 204));

        AdminBackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AdminBackButton.setText("Back to previous menu");
        AdminBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBackButtonActionPerformed(evt);
            }
        });

        AdminDisplayArea.setColumns(20);
        AdminDisplayArea.setLineWrap(true);
        AdminDisplayArea.setRows(6);
        AdminDisplayArea.setWrapStyleWord(true);
        AdminDisplayArea.setFocusable(false);
        jScrollPane2.setViewportView(AdminDisplayArea);

        MaintenanceLabel.setBackground(new java.awt.Color(255, 204, 102));
        MaintenanceLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        MaintenanceLabel.setForeground(new java.awt.Color(255, 102, 255));
        MaintenanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaintenanceLabel.setText("Maintenance Panel (Admins Only)");
        MaintenanceLabel.setAlignmentY(0.0F);
        MaintenanceLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MaintenanceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MaintenanceLabel.setMaximumSize(new java.awt.Dimension(50, 34));
        MaintenanceLabel.setMinimumSize(new java.awt.Dimension(50, 34));
        MaintenanceLabel.setName(""); // NOI18N
        MaintenanceLabel.setOpaque(true);
        MaintenanceLabel.setPreferredSize(new java.awt.Dimension(50, 34));

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addComponent(MaintenanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(AdminBackButton)
                        .addGap(69, 69, 69))))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaintenanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminBackButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdminFrameRegularLayout = new javax.swing.GroupLayout(AdminFrameRegular.getContentPane());
        AdminFrameRegular.getContentPane().setLayout(AdminFrameRegularLayout);
        AdminFrameRegularLayout.setHorizontalGroup(
            AdminFrameRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminFrameRegularLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AdminFrameRegularLayout.setVerticalGroup(
            AdminFrameRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminFrameRegularLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        SpecialMachineCustom.setResizable(false);
        SpecialMachineCustom.setSize(new java.awt.Dimension(450, 330));
        SpecialMachineCustom.setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout SpecialMachinePanelLayout = new javax.swing.GroupLayout(SpecialMachinePanel);
        SpecialMachinePanel.setLayout(SpecialMachinePanelLayout);
        SpecialMachinePanelLayout.setHorizontalGroup(
            SpecialMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        SpecialMachinePanelLayout.setVerticalGroup(
            SpecialMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SpecialMachineCustomLayout = new javax.swing.GroupLayout(SpecialMachineCustom.getContentPane());
        SpecialMachineCustom.getContentPane().setLayout(SpecialMachineCustomLayout);
        SpecialMachineCustomLayout.setHorizontalGroup(
            SpecialMachineCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecialMachineCustomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SpecialMachinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SpecialMachineCustomLayout.setVerticalGroup(
            SpecialMachineCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecialMachineCustomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SpecialMachinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vending Machine MCO2");
        setResizable(false);

        BigMachinePanel.setBackground(new java.awt.Color(204, 204, 204));

        VendingMachineName.setBackground(new java.awt.Color(255, 204, 102));
        VendingMachineName.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        VendingMachineName.setForeground(new java.awt.Color(255, 102, 255));
        VendingMachineName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VendingMachineName.setText("Vending Machine Name Here");
        VendingMachineName.setAlignmentY(0.0F);
        VendingMachineName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VendingMachineName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        VendingMachineName.setMaximumSize(new java.awt.Dimension(50, 34));
        VendingMachineName.setMinimumSize(new java.awt.Dimension(50, 34));
        VendingMachineName.setName(""); // NOI18N
        VendingMachineName.setOpaque(true);
        VendingMachineName.setPreferredSize(new java.awt.Dimension(50, 34));

        InputPanel.setBackground(new java.awt.Color(255, 255, 255));

        ClearButton.setText("CLEAR");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        amountGetterButton.setText("ENTER");
        amountGetterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountGetterButtonActionPerformed(evt);
            }
        });

        InsertMoneyButton.setText("Insert Money");
        InsertMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMoneyButtonActionPerformed(evt);
            }
        });

        MachineButtonPanel.setBackground(new java.awt.Color(204, 255, 255));

        jButtonCreate1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate1.setText("1");
        jButtonCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate1ActionPerformed(evt);
            }
        });

        jButtonCreate2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate2.setText("2");
        jButtonCreate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate2ActionPerformed(evt);
            }
        });

        jButtonCreate3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate3.setText("3");
        jButtonCreate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate3ActionPerformed(evt);
            }
        });

        jButtonCreate4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate4.setText("4");
        jButtonCreate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate4ActionPerformed(evt);
            }
        });

        jButtonCreate5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate5.setText("5");
        jButtonCreate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate5ActionPerformed(evt);
            }
        });

        jButtonCreate6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate6.setText("6");
        jButtonCreate6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate6ActionPerformed(evt);
            }
        });

        jButtonCreate7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate7.setText("7");
        jButtonCreate7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate7ActionPerformed(evt);
            }
        });

        jButtonCreate8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate8.setText("8");
        jButtonCreate8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate8ActionPerformed(evt);
            }
        });

        jButtonCreate9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate9.setText("9");
        jButtonCreate9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate9ActionPerformed(evt);
            }
        });

        jButtonCreate0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCreate0.setText("0");
        jButtonCreate0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MachineButtonPanelLayout = new javax.swing.GroupLayout(MachineButtonPanel);
        MachineButtonPanel.setLayout(MachineButtonPanelLayout);
        MachineButtonPanelLayout.setHorizontalGroup(
            MachineButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MachineButtonPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(MachineButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MachineButtonPanelLayout.createSequentialGroup()
                        .addComponent(jButtonCreate1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate4)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate5))
                    .addGroup(MachineButtonPanelLayout.createSequentialGroup()
                        .addComponent(jButtonCreate6)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate7)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate8)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate9)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate0)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        MachineButtonPanelLayout.setVerticalGroup(
            MachineButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MachineButtonPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(MachineButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreate5)
                    .addComponent(jButtonCreate4)
                    .addComponent(jButtonCreate3)
                    .addComponent(jButtonCreate2)
                    .addComponent(jButtonCreate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MachineButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreate6)
                    .addComponent(jButtonCreate7)
                    .addComponent(jButtonCreate0)
                    .addComponent(jButtonCreate8)
                    .addComponent(jButtonCreate9))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amountGetterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsertMoneyButton))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(MachineButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MachineButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton)
                    .addComponent(amountGetterButton)
                    .addComponent(InsertMoneyButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        LayoutPanel.setMaximumSize(new java.awt.Dimension(526, 486));

        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton21.setText("ADMIN SETTINGS");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ExitButton.setText("EXIT MACHINE");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        MachineBalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MachineBalLabel.setText("MACHINE BALANCE: 0");

        PersonBalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PersonBalLabel.setText("BALANCE: 0");

        ExitButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ExitButton1.setText("DISPENSE");
        ExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton1ActionPerformed(evt);
            }
        });

        BuyItemPanel.setBackground(new java.awt.Color(204, 204, 204));

        Item1Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item1Buy.setText("BUY");

        Item2Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item2Buy.setText("BUY");

        Item3Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item3Buy.setText("BUY");

        Item4Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item4Buy.setText("BUY");

        Item5Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item5Buy.setText("BUY");

        Item6Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item6Buy.setText("BUY");

        Item8Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item8Buy.setText("BUY");

        Item7Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item7Buy.setText("BUY");

        Ing1Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ing1Buy.setText("BUY");
        Ing1Buy.setEnabled(false);

        Ing2Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ing2Buy.setText("BUY");
        Ing2Buy.setEnabled(false);

        Ing3Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ing3Buy.setText("BUY");
        Ing3Buy.setEnabled(false);

        Ing4Buy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ing4Buy.setText("BUY");
        Ing4Buy.setEnabled(false);

        Item1Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item1Label.setText(Model.getItem1Name());
        Item1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item2Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item2Label.setText(Model.getItem2Name());
        Item2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item4Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item4Label.setText(Model.getItem4Name());
        Item4Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item3Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item3Label.setText(Model.getItem3Name());
        Item3Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item5Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item5Label.setText(Model.getItem5Name());
        Item5Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item6Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item6Label.setText(Model.getItem6Name());
        Item6Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item7Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item7Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item7Label.setText(Model.getItem7Name());
        Item7Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item8Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item8Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item8Label.setText(Model.getItem8Name());
        Item8Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item9Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item9Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item9Label.setText("Item1Name");
        Item9Label.setEnabled(false);
        Item9Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item1Label9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item1Label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item1Label9.setText("Item1Name");
        Item1Label9.setEnabled(false);
        Item1Label9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item1Label10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item1Label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item1Label10.setText("Item1Name");
        Item1Label10.setEnabled(false);
        Item1Label10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Item1Label11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Item1Label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item1Label11.setText("Item1Name");
        Item1Label11.setEnabled(false);
        Item1Label11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout BuyItemPanelLayout = new javax.swing.GroupLayout(BuyItemPanel);
        BuyItemPanel.setLayout(BuyItemPanelLayout);
        BuyItemPanelLayout.setHorizontalGroup(
            BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuyItemPanelLayout.createSequentialGroup()
                .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Item9Label)
                    .addComponent(Item5Label)
                    .addComponent(Ing1Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuyItemPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Item5Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BuyItemPanelLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Item1Label)
                                .addComponent(Item1Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25)
                .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Item6Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item2Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item2Label)
                    .addComponent(Item6Label)
                    .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Item1Label9)
                        .addComponent(Ing2Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Item3Label)
                            .addComponent(Item7Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item3Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Item7Label))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Item1Label10)
                        .addComponent(Ing3Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item8Label)
                    .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Item8Buy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Item4Buy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ing4Buy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Item4Label))
                    .addComponent(Item1Label11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );
        BuyItemPanelLayout.setVerticalGroup(
            BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuyItemPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item1Label)
                    .addComponent(Item2Label)
                    .addComponent(Item4Label)
                    .addComponent(Item3Label))
                .addGap(25, 25, 25)
                .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item1Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item2Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item3Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item4Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item5Label)
                    .addComponent(Item6Label)
                    .addComponent(Item7Label)
                    .addComponent(Item8Label))
                .addGap(25, 25, 25)
                .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item5Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item6Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item7Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item8Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item9Label)
                    .addComponent(Item1Label9)
                    .addComponent(Item1Label10)
                    .addComponent(Item1Label11))
                .addGap(25, 25, 25)
                .addGroup(BuyItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ing1Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ing2Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ing3Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ing4Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout LayoutPanelLayout = new javax.swing.GroupLayout(LayoutPanel);
        LayoutPanel.setLayout(LayoutPanelLayout);
        LayoutPanelLayout.setHorizontalGroup(
            LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutPanelLayout.createSequentialGroup()
                .addGroup(LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayoutPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(MachineBalLabel)
                        .addGap(205, 205, 205)
                        .addComponent(PersonBalLabel))
                    .addGroup(LayoutPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LayoutPanelLayout.createSequentialGroup()
                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(ExitButton)
                                .addGap(15, 15, 15)
                                .addComponent(ExitButton1))
                            .addComponent(BuyItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        LayoutPanelLayout.setVerticalGroup(
            LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BuyItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(jButton21)
                    .addComponent(ExitButton1))
                .addGap(20, 20, 20)
                .addGroup(LayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MachineBalLabel)
                    .addComponent(PersonBalLabel))
                .addGap(25, 25, 25))
        );

        NumPadDisplay.setEditable(false);
        NumPadDisplay.setBackground(new java.awt.Color(255, 255, 204));
        NumPadDisplay.setColumns(20);
        NumPadDisplay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NumPadDisplay.setLineWrap(true);
        NumPadDisplay.setRows(6);
        NumPadDisplay.setWrapStyleWord(true);
        NumPadDisplay.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(NumPadDisplay);

        MachinePrintDisplay.setEditable(false);
        MachinePrintDisplay.setBackground(new java.awt.Color(204, 255, 204));
        MachinePrintDisplay.setColumns(20);
        MachinePrintDisplay.setLineWrap(true);
        MachinePrintDisplay.setRows(6);
        MachinePrintDisplay.setWrapStyleWord(true);
        MachinePrintDisplay.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(MachinePrintDisplay);

        javax.swing.GroupLayout BigMachinePanelLayout = new javax.swing.GroupLayout(BigMachinePanel);
        BigMachinePanel.setLayout(BigMachinePanelLayout);
        BigMachinePanelLayout.setHorizontalGroup(
            BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BigMachinePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VendingMachineName, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)
                    .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        BigMachinePanelLayout.setVerticalGroup(
            BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BigMachinePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BigMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(BigMachinePanelLayout.createSequentialGroup()
                        .addComponent(VendingMachineName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BigMachinePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        VendingMachineName.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(BigMachinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(BigMachinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate4ActionPerformed
        if (NumPadDisplay.getText().equals("TEXT GOES HERE") )
         NumPadDisplay.setText("4");
     else
        NumPadDisplay.setText(NumPadDisplay.getText() + "4");
    }//GEN-LAST:event_jButtonCreate4ActionPerformed

    private void jButtonCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate1ActionPerformed
     if (NumPadDisplay.getText().equals("TEXT GOES HERE") )
         NumPadDisplay.setText("1");
     else
        NumPadDisplay.setText(NumPadDisplay.getText() + "1");
    }//GEN-LAST:event_jButtonCreate1ActionPerformed

    private void jButtonCreate6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate6ActionPerformed
        if (NumPadDisplay.getText().equals("TEXT GOES HERE") )
         NumPadDisplay.setText("6");
     else
        NumPadDisplay.setText(NumPadDisplay.getText() + "6");
    }//GEN-LAST:event_jButtonCreate6ActionPerformed

    private void jButtonCreate8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate8ActionPerformed
        if (NumPadDisplay.getText().equals("TEXT GOES HERE") )
         NumPadDisplay.setText("8");
     else
        NumPadDisplay.setText(NumPadDisplay.getText() + "8");
    }//GEN-LAST:event_jButtonCreate8ActionPerformed

    private void jButtonCreate7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate7ActionPerformed
        if (NumPadDisplay.getText().equals("TEXT GOES HERE") )
         NumPadDisplay.setText("7");
     else
        NumPadDisplay.setText(NumPadDisplay.getText() + "7");
    }//GEN-LAST:event_jButtonCreate7ActionPerformed

    private void jButtonCreate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate5ActionPerformed
        if (NumPadDisplay.getText().equals("TEXT GOES HERE") )
         NumPadDisplay.setText("5");
     else
        NumPadDisplay.setText(NumPadDisplay.getText() + "5");
    }//GEN-LAST:event_jButtonCreate5ActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
       //Back Space
       NumPadDisplay.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void jButtonCreate9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate9ActionPerformed
        if (NumPadDisplay.getText().equals("TEXT GOES HERE") )
         NumPadDisplay.setText("9");
     else
        NumPadDisplay.setText(NumPadDisplay.getText() + "9");
    }//GEN-LAST:event_jButtonCreate9ActionPerformed

    private void jButtonCreate0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate0ActionPerformed
        if (NumPadDisplay.getText().equals("TEXT GOES HERE") )
         NumPadDisplay.setText("0");
     else
        NumPadDisplay.setText(NumPadDisplay.getText() + "0");
    }//GEN-LAST:event_jButtonCreate0ActionPerformed

    private void amountGetterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountGetterButtonActionPerformed
        try {
            this.quantityBuy = Integer.parseInt(NumPadDisplay.getText() );
        } catch (Exception e) {
            this.quantityBuy = -999;
        }
    }//GEN-LAST:event_amountGetterButtonActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        AdminFrameRegular.setVisible(true);
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButtonCreate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate2ActionPerformed
     if (NumPadDisplay.getText().equals("TEXT GOES HERE") )
         NumPadDisplay.setText("2");
     else
        NumPadDisplay.setText(NumPadDisplay.getText() + "2");
    }//GEN-LAST:event_jButtonCreate2ActionPerformed

    private void jButtonCreate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate3ActionPerformed
        if (NumPadDisplay.getText().equals("TEXT GOES HERE") )
         NumPadDisplay.setText("3");
     else
        NumPadDisplay.setText(NumPadDisplay.getText() + "3");
    }//GEN-LAST:event_jButtonCreate3ActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AdminBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBackButtonActionPerformed
        AdminFrameRegular.dispose();
    }//GEN-LAST:event_AdminBackButtonActionPerformed

    private void InsertMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMoneyButtonActionPerformed
       int temp = 0;
        try {
          temp = Integer.parseInt(NumPadDisplay.getText());
          balLabel += temp;
       } catch (Exception e) {
          temp = 0;
       }
       PersonBalLabel.setText ( "BALANCE: " + balLabel);
       NumPadDisplay.setText("");
    }//GEN-LAST:event_InsertMoneyButtonActionPerformed

    private void ExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButton1ActionPerformed

}
    /**
     * @param args the command line arguments
     */
    
    
  // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(new Runnable() {
     //       public void run() {
    //        }
    //    });
  //  } 

 
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBackButton;
    private javax.swing.JTextArea AdminDisplayArea;
    private javax.swing.JFrame AdminFrameRegular;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel BigMachinePanel;
    private javax.swing.JPanel BuyItemPanel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ExitButton1;
    private javax.swing.JButton Ing1Buy;
    private javax.swing.JButton Ing2Buy;
    private javax.swing.JButton Ing3Buy;
    private javax.swing.JButton Ing4Buy;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JButton InsertMoneyButton;
    private javax.swing.JButton Item1Buy;
    private javax.swing.JLabel Item1Label;
    private javax.swing.JLabel Item1Label10;
    private javax.swing.JLabel Item1Label11;
    private javax.swing.JLabel Item1Label9;
    private javax.swing.JButton Item2Buy;
    private javax.swing.JLabel Item2Label;
    private javax.swing.JButton Item3Buy;
    private javax.swing.JLabel Item3Label;
    private javax.swing.JButton Item4Buy;
    private javax.swing.JLabel Item4Label;
    private javax.swing.JButton Item5Buy;
    private javax.swing.JLabel Item5Label;
    private javax.swing.JButton Item6Buy;
    private javax.swing.JLabel Item6Label;
    private javax.swing.JButton Item7Buy;
    private javax.swing.JLabel Item7Label;
    private javax.swing.JButton Item8Buy;
    private javax.swing.JLabel Item8Label;
    private javax.swing.JLabel Item9Label;
    private javax.swing.JPanel LayoutPanel;
    private javax.swing.JLabel MachineBalLabel;
    private javax.swing.JPanel MachineButtonPanel;
    private javax.swing.JTextArea MachinePrintDisplay;
    private javax.swing.JLabel MaintenanceLabel;
    private javax.swing.JTextArea NumPadDisplay;
    private javax.swing.JLabel PersonBalLabel;
    private javax.swing.JFrame SpecialMachineCustom;
    private javax.swing.JPanel SpecialMachinePanel;
    private javax.swing.JLabel VendingMachineName;
    private javax.swing.JButton amountGetterButton;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButtonCreate0;
    private javax.swing.JButton jButtonCreate1;
    private javax.swing.JButton jButtonCreate2;
    private javax.swing.JButton jButtonCreate3;
    private javax.swing.JButton jButtonCreate4;
    private javax.swing.JButton jButtonCreate5;
    private javax.swing.JButton jButtonCreate6;
    private javax.swing.JButton jButtonCreate7;
    private javax.swing.JButton jButtonCreate8;
    private javax.swing.JButton jButtonCreate9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
*/