/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIINTERFACE;
import javax.swing.*;

/**
 *
 * @author kurvy
 */
public class TestVendingMachine extends javax.swing.JFrame {
    private String machineName;
    private JLabel jLabel2;
    private JButton jButtonCreate4;
    private JButton jButtonCreate9;
    private JButton jButtonCreate0;
    private JButton jButton12;
    private JButton jButton13;
    private JButton jButton14;
    private JButton jButton15;
    private JButton jButton16;
    private JButton jButton17;
    private JButton jButton18;
    private JButton jButton19;
    private JButton jButtonCreate3;
    private JButton jButton20;
    private JButton jButton21;
    private JButton jButton22;
    private JButton jButton23;
    private JButton jButton24;
    private JButton jButton25;
    private JButton jButton26;
    private JButton jButton27;
    private JButton jButton28;
    private JButton jButton29;
    private JButton jButtonCreate2;
    private JButton jButton30;
    private JButton jButtonCreate1;
    private JButton jButtonCreate6;
    private JButton jButtonCreate8;
    private JButton jButtonCreate7;
    private JButton jButtonCreate5;
    private JButton ClearButton;
    private JFrame jFrame1;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JTextArea AdminDisplayArea;
    private JScrollPane jScrollPane3;
    private JTextArea MachineDisplayArea;
    
    public TestVendingMachine() {
        try{
           initComponents();
           this.machineName = "Vending Machine";
        } catch (Exception e)
        {
           initComponents();
           this.machineName = "Vending Machine";
           System.out.println("NO NAME DETECTED! GENERATING DEFAULT NAME...");
        }
    }
    
    public TestVendingMachine(String name) {
        try{
           initComponents();
           this.machineName = name;
        } catch (Exception e)
        {
           initComponents();
           this.machineName = "Vending Machine";
           System.out.println("NAME IS INVALID. GENERATING OWN NAME.");
        }
    }
    
    public String getName(){
        return this.machineName;
    }
    
    public void setName(String name){
        this.machineName = name;
    }
    
    public void setmachineLabel(String text){
        this.jLabel1.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AdminDisplayArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonCreate3 = new javax.swing.JButton();
        jButtonCreate4 = new javax.swing.JButton();
        jButtonCreate2 = new javax.swing.JButton();
        jButtonCreate1 = new javax.swing.JButton();
        jButtonCreate6 = new javax.swing.JButton();
        jButtonCreate8 = new javax.swing.JButton();
        jButtonCreate7 = new javax.swing.JButton();
        jButtonCreate5 = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jButtonCreate9 = new javax.swing.JButton();
        jButtonCreate0 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        MachineDisplayArea = new javax.swing.JTextArea();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jButton22.setText("jButton22");

        jButton23.setText("jButton23");

        jButton24.setText("jButton24");

        jButton25.setText("jButton25");

        jButton26.setText("jButton26");

        jButton27.setText("jButton27");

        jButton28.setText("jButton28");

        jButton29.setText("jButton29");

        jButton30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton30.setText("Back to previous menu");

        AdminDisplayArea.setColumns(20);
        AdminDisplayArea.setRows(5);
        AdminDisplayArea.setFocusable(false);
        jScrollPane2.setViewportView(AdminDisplayArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton30)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton26)
                                    .addComponent(jButton22))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton23)
                                    .addComponent(jButton27))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton24)
                                    .addComponent(jButton28))))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton25)
                            .addComponent(jButton29))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton25)
                    .addComponent(jButton24)
                    .addComponent(jButton23)
                    .addComponent(jButton22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton26)
                    .addComponent(jButton27)
                    .addComponent(jButton28)
                    .addComponent(jButton29))
                .addGap(43, 43, 43)
                .addComponent(jButton30)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vending Machine MCO2");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vending Machine Name Here");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButtonCreate3.setText("3");
        jButtonCreate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate3ActionPerformed(evt);
            }
        });

        jButtonCreate4.setText("4");
        jButtonCreate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate4ActionPerformed(evt);
            }
        });

        jButtonCreate2.setText("2");
        jButtonCreate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate2ActionPerformed(evt);
            }
        });

        jButtonCreate1.setText("1");
        jButtonCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate1ActionPerformed(evt);
            }
        });

        jButtonCreate6.setText("6");
        jButtonCreate6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate6ActionPerformed(evt);
            }
        });

        jButtonCreate8.setText("8");
        jButtonCreate8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate8ActionPerformed(evt);
            }
        });

        jButtonCreate7.setText("7");
        jButtonCreate7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate7ActionPerformed(evt);
            }
        });

        jButtonCreate5.setText("5");
        jButtonCreate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate5ActionPerformed(evt);
            }
        });

        ClearButton.setText("CLEAR");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        jButtonCreate9.setText("9");
        jButtonCreate9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate9ActionPerformed(evt);
            }
        });

        jButtonCreate0.setText("0");
        jButtonCreate0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreate0ActionPerformed(evt);
            }
        });

        jButton12.setText("ENTER");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonCreate6)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate7)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate8)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate9)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate0))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonCreate1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate4)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreate5)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreate3)
                    .addComponent(jButtonCreate2)
                    .addComponent(jButtonCreate1)
                    .addComponent(jButtonCreate4)
                    .addComponent(jButtonCreate5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreate6)
                    .addComponent(jButtonCreate7)
                    .addComponent(jButtonCreate8)
                    .addComponent(jButtonCreate9)
                    .addComponent(jButtonCreate0))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton)
                    .addComponent(jButton12))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton13.setText("BUY");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("BUY");

        jButton15.setText("BUY");

        jButton16.setText("BUY");

        jButton17.setText("BUY");

        jButton18.setText("BUY");

        jButton19.setText("BUY");

        jButton20.setText("BUY");

        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton21.setText("ADMIN SETTINGS");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton13)
                                .addGap(15, 15, 15)
                                .addComponent(jButton14)
                                .addGap(15, 15, 15)
                                .addComponent(jButton19))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton17)
                                .addGap(15, 15, 15)
                                .addComponent(jButton18)
                                .addGap(15, 15, 15)
                                .addComponent(jButton20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton15)
                            .addComponent(jButton16)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton21)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13)
                    .addComponent(jButton16)
                    .addComponent(jButton14)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton17)
                    .addComponent(jButton18)
                    .addComponent(jButton20)
                    .addComponent(jButton15))
                .addGap(36, 36, 36)
                .addComponent(jButton21)
                .addGap(29, 29, 29))
        );

        MachineDisplayArea.setEditable(false);
        MachineDisplayArea.setColumns(20);
        MachineDisplayArea.setLineWrap(true);
        MachineDisplayArea.setRows(6);
        MachineDisplayArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(MachineDisplayArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate4ActionPerformed
        if (MachineDisplayArea.getText().equals("TEXT GOES HERE") )
         MachineDisplayArea.setText("4");
     else
        MachineDisplayArea.setText( MachineDisplayArea.getText() + "4");
    }//GEN-LAST:event_jButtonCreate4ActionPerformed

    private void jButtonCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate1ActionPerformed
     if (MachineDisplayArea.getText().equals("TEXT GOES HERE") )
         MachineDisplayArea.setText("1");
     else
        MachineDisplayArea.setText(MachineDisplayArea.getText() + "1");
    }//GEN-LAST:event_jButtonCreate1ActionPerformed

    private void jButtonCreate6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate6ActionPerformed
        if (MachineDisplayArea.getText().equals("TEXT GOES HERE") )
         MachineDisplayArea.setText("6");
     else
        MachineDisplayArea.setText( MachineDisplayArea.getText() + "6");
    }//GEN-LAST:event_jButtonCreate6ActionPerformed

    private void jButtonCreate8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate8ActionPerformed
        if (MachineDisplayArea.getText().equals("TEXT GOES HERE") )
         MachineDisplayArea.setText("8");
     else
        MachineDisplayArea.setText( MachineDisplayArea.getText() + "8");
    }//GEN-LAST:event_jButtonCreate8ActionPerformed

    private void jButtonCreate7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate7ActionPerformed
        if (MachineDisplayArea.getText().equals("TEXT GOES HERE") )
         MachineDisplayArea.setText("7");
     else
        MachineDisplayArea.setText( MachineDisplayArea.getText() + "7");
    }//GEN-LAST:event_jButtonCreate7ActionPerformed

    private void jButtonCreate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate5ActionPerformed
        if (MachineDisplayArea.getText().equals("TEXT GOES HERE") )
         MachineDisplayArea.setText("5");
     else
        MachineDisplayArea.setText( MachineDisplayArea.getText() + "5");
    }//GEN-LAST:event_jButtonCreate5ActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
       //Back Space
       MachineDisplayArea.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void jButtonCreate9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate9ActionPerformed
        if (MachineDisplayArea.getText().equals("TEXT GOES HERE") )
         MachineDisplayArea.setText("9");
     else
        MachineDisplayArea.setText( MachineDisplayArea.getText() + "9");
    }//GEN-LAST:event_jButtonCreate9ActionPerformed

    private void jButtonCreate0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate0ActionPerformed
        if (MachineDisplayArea.getText().equals("TEXT GOES HERE") )
         MachineDisplayArea.setText("0");
     else
        MachineDisplayArea.setText( MachineDisplayArea.getText() + "0");
    }//GEN-LAST:event_jButtonCreate0ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         MachineDisplayArea.setText("This function is yet to be implemented.");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        jFrame1.setVisible(true);
        jFrame1.setSize(595, 410);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButtonCreate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate2ActionPerformed
     if (MachineDisplayArea.getText().equals("TEXT GOES HERE") )
         MachineDisplayArea.setText("2");
     else
        MachineDisplayArea.setText( MachineDisplayArea.getText() + "2");
    }//GEN-LAST:event_jButtonCreate2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButtonCreate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreate3ActionPerformed
        if (MachineDisplayArea.getText().equals("TEXT GOES HERE") )
         MachineDisplayArea.setText("3");
     else
        MachineDisplayArea.setText( MachineDisplayArea.getText() + "3");
    }//GEN-LAST:event_jButtonCreate3ActionPerformed
}
    /**
     * @param args the command line arguments
     */
    
    
  // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(new Runnable() {
     //       public void run() {
    //        }
    //    });
  //  } 

 
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AdminDisplayArea;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextArea MachineDisplayArea;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButtonCreate0;
    private javax.swing.JButton jButtonCreate1;
    private javax.swing.JButton jButtonCreate2;
    private javax.swing.JButton jButtonCreate3;
    private javax.swing.JButton jButtonCreate4;
    private javax.swing.JButton jButtonCreate5;
    private javax.swing.JButton jButtonCreate6;
    private javax.swing.JButton jButtonCreate7;
    private javax.swing.JButton jButtonCreate8;
    private javax.swing.JButton jButtonCreate9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
*/